# Generated by Django 5.2.16 on 2026-07-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_fr",
                    models.CharField(max_length=100, verbose_name="nom (français)"),
                ),
                (
                    "nom_ln",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nom (lingala)"
                    ),
                ),
                (
                    "nom_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nom (anglais)"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "photos_obligatoires",
                    models.BooleanField(
                        default=False,
                        help_text="Au moins une photo exigée à la publication (décision Q7).",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "catégorie",
                "ordering": ["ordre", "nom_fr"],
            },
        ),
        migrations.CreateModel(
            name="ChampCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_fr",
                    models.CharField(max_length=100, verbose_name="nom (français)"),
                ),
                (
                    "nom_ln",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nom (lingala)"
                    ),
                ),
                (
                    "nom_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nom (anglais)"
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Identifiant stable du champ, utilisé pour stocker les valeurs des annonces.",
                        verbose_name="code technique",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("texte", "Texte"),
                            ("nombre", "Nombre"),
                            ("liste", "Liste de valeurs"),
                        ],
                        default="texte",
                        max_length=10,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Valeurs proposées pour un champ de type « liste » (une par ligne).",
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : m², km",
                        max_length=20,
                        verbose_name="unité",
                    ),
                ),
                ("obligatoire", models.BooleanField(default=False)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champs",
                        to="annonces.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "champ de catégorie",
                "verbose_name_plural": "champs de catégorie",
                "ordering": ["ordre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("categorie", "code"),
                        name="champ_code_unique_par_categorie",
                    )
                ],
            },
        ),
    ]
