# Generated by Django 5.2.16 on 2026-07-21 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0002_categories_du_lancement"),
        ("geo", "0002_communes_de_kinshasa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=120, verbose_name="titre")),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("description", models.TextField(verbose_name="description")),
                (
                    "prix",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="prix",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USD", "$ (dollars américains)"),
                            ("CDF", "FC (francs congolais)"),
                        ],
                        max_length=3,
                        verbose_name="devise",
                    ),
                ),
                (
                    "prix_a_discuter",
                    models.BooleanField(default=False, verbose_name="prix à discuter"),
                ),
                (
                    "contact",
                    models.CharField(
                        choices=[
                            ("telephone", "Numéro affiché sur l'annonce"),
                            ("messagerie", "Messagerie interne uniquement"),
                        ],
                        default="telephone",
                        max_length=12,
                        verbose_name="mode de contact",
                    ),
                ),
                ("attributs", models.JSONField(blank=True, default=dict)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("publiee", "Publiée"),
                            ("retiree", "Retirée par le vendeur"),
                            ("suspendue", "Suspendue par la modération"),
                        ],
                        default="publiee",
                        max_length=12,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_publication", models.DateTimeField(db_index=True)),
                (
                    "premium_jusqu_au",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annonces",
                        to="annonces.categorie",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annonces",
                        to="geo.commune",
                    ),
                ),
                (
                    "vendeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annonces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "annonce",
                "ordering": ["-date_publication"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="annonces/%Y/%m/")),
                ("ordre", models.PositiveSmallIntegerField(default=1)),
                (
                    "annonce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="annonces.annonce",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="ClicAffichageNumero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "annonce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clics_numero",
                        to="annonces.annonce",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clics_numero",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "clic « afficher le numéro »",
                "verbose_name_plural": "clics « afficher le numéro »",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("annonce", "utilisateur"),
                        name="un_clic_par_annonce_et_utilisateur",
                    )
                ],
            },
        ),
    ]
