# Generated by Django 5.2.16 on 2026-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0003_annonce_photo_clicaffichagenumero"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="vignette",
            field=models.ImageField(blank=True, upload_to="annonces/%Y/%m/vignettes/"),
        ),
    ]
