# Generated by Django 5.2.16 on 2026-07-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("annonces", "0003_annonce_photo_clicaffichagenumero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotifFrauduleux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expression",
                    models.CharField(
                        max_length=120,
                        unique=True,
                        verbose_name="expression à détecter",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "motif frauduleux (anti-spam)",
                "verbose_name_plural": "motifs frauduleux (anti-spam)",
            },
        ),
        migrations.CreateModel(
            name="MotifSignalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_fr",
                    models.CharField(max_length=100, verbose_name="nom (français)"),
                ),
                (
                    "nom_ln",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nom (lingala)"
                    ),
                ),
                (
                    "nom_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nom (anglais)"
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "motif de signalement",
                "verbose_name_plural": "motifs de signalement",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="MarqueAntiSpam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regle",
                    models.CharField(max_length=5, verbose_name="règle déclenchée"),
                ),
                (
                    "detail",
                    models.CharField(blank=True, max_length=200, verbose_name="détail"),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("rejetee", "Rejetée (fausse alerte)"),
                            ("traitee", "Traitée"),
                        ],
                        default="en_attente",
                        max_length=10,
                    ),
                ),
                (
                    "annonce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marques_antispam",
                        to="annonces.annonce",
                    ),
                ),
            ],
            options={
                "verbose_name": "marque anti-spam",
                "verbose_name_plural": "marques anti-spam",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="commentaire"),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("rejete", "Rejeté"),
                            ("traite", "Traité"),
                        ],
                        default="en_attente",
                        max_length=10,
                    ),
                ),
                (
                    "annonce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalements",
                        to="annonces.annonce",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vide pour un visiteur non connecté.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signalements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "motif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="moderation.motifsignalement",
                    ),
                ),
            ],
            options={
                "verbose_name": "signalement",
                "ordering": ["-date"],
            },
        ),
    ]
