# Generated by Django 5.2.16 on 2026-07-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "actif",
                    models.BooleanField(
                        default=False,
                        help_text="Seules les villes actives apparaissent dans les formulaires et filtres.",
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "verbose_name": "ville",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
                ("slug", models.SlugField()),
                ("actif", models.BooleanField(default=True, verbose_name="active")),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communes",
                        to="geo.ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "commune",
                "ordering": ["nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ville", "nom"), name="commune_nom_unique_par_ville"
                    ),
                    models.UniqueConstraint(
                        fields=("ville", "slug"), name="commune_slug_unique_par_ville"
                    ),
                ],
            },
        ),
    ]
